#ifndef HK_CAMERA_CONFIG_H
#define HK_CAMERA_CONFIG_H

#define CAMERA_FRAME_TIMEOUT_US 150000ULL
#define CAMERA_REVIEW_MS 2500

#define CAMERA_SCCB_ADDR 0x60
#define CAMERA_XCLK_HZ 40000000U
#define CAMERA_SCCB_HZ 100000U
#define CAMERA_MAX_W 640U
#define CAMERA_MAX_H 480U
#define CAMERA_MAX_FRAME_PIXELS (CAMERA_MAX_W * CAMERA_MAX_H)
#define PHOTO_VIEW_MAX_W 1600U
#define PHOTO_VIEW_MAX_H 1200U
#define PHOTO_ROW_MAX_BYTES (PHOTO_VIEW_MAX_W * 3U)
#define CAMERA_FRAME_WAIT_MS 90

#define QR_DECODE_RATE_DEFAULT 5U
#define QR_DECODE_RATE_MIN 1U
#define QR_DECODE_RATE_MAX 5U
#define QR_AUTOSCAN_W 320U
#define QR_AUTOSCAN_H 240U
#define QR_PAYLOAD_MAX 384
#define QR_STATUS_LOG_INTERVAL_US 2000000ULL
#define QR_PASS_INVERT 0x01U
#define QR_PASS_STRETCH 0x02U

#endif
