#ifndef HK_CAMERA_CONFIG_H
#define HK_CAMERA_CONFIG_H

#define CAMERA_FRAME_TIMEOUT_US 150000ULL
#define CAMERA_SCCB_ADDR 0x60
#define CAMERA_XCLK_HZ 40000000U
#define CAMERA_SCCB_HZ 100000U
#define CAMERA_MAX_W 640U
#define CAMERA_MAX_H 480U
#define CAMERA_MAX_FRAME_PIXELS (CAMERA_MAX_W * CAMERA_MAX_H)
#define CAMERA_FRAME_WAIT_MS 90

#endif
