#ifndef HK_PHOTO_STORAGE_CONFIG_H
#define HK_PHOTO_STORAGE_CONFIG_H

#define PHOTO_DIR_LONG_NAME "hackylens.photo"
#define QR_DIR_LONG_NAME "hackylens.qr"
#define SCREENSHOT_DIR_LONG_NAME "hackylens.screen"

#define PHOTO_BMP_BPP 24U
#define PHOTO_BMP_HEADER_SIZE 54U
#define PHOTO_BMP565_HEADER_SIZE 66U
#define PHOTO_PPM_HEADER_MAX 32U
#define SCREENSHOT_BMP_HEADER_SIZE PHOTO_BMP_HEADER_SIZE

#endif
