#ifndef HK_SETTINGS_LAYOUT_H
#define HK_SETTINGS_LAYOUT_H

#define SETTINGS_ROW_Y0 40
#define SETTINGS_ROW_H 31
#define SETTINGS_VISIBLE_ROWS 6
#define SETTINGS_VALUE_W 56
#define SETTINGS_REPEAT_INITIAL_TICKS 12
#define SETTINGS_REPEAT_NEXT_TICKS 4

#endif
