#ifndef HK_SETTINGS_CONFIG_H
#define HK_SETTINGS_CONFIG_H

#define SETTINGS_ROW_COUNT 9
#define SETTINGS_LED_SWITCH 0
#define SETTINGS_LED_BRIGHTNESS 1
#define SETTINGS_RGB_SWITCH 2
#define SETTINGS_RGB_RED 3
#define SETTINGS_RGB_GREEN 4
#define SETTINGS_RGB_BLUE 5
#define SETTINGS_SCREEN_BRIGHTNESS 6
#define SETTINGS_AUTO_SLEEP 7
#define SETTINGS_VERSION 8

#define SETTINGS_SAVE_DELAY_TICKS 25
#define SETTINGS_FLASH_SLOT0 0x007FE000UL
#define SETTINGS_FLASH_SLOT1 0x007FF000UL
#define SETTINGS_FLASH_SLOT_SIZE 4096U
#define SETTINGS_FLASH_MIN_CAPACITY_LOG2 23U
#define SETTINGS_MAGIC 0x484B5331UL
#define SETTINGS_STORAGE_VERSION 1U
#define SETTINGS_RGB_MARK 0xC3U
#define SETTINGS_FPS_MARK 0xF5U
#define SETTINGS_CAMERA_MARK_V1 0xA5U
#define SETTINGS_CAMERA_MARK 0xA6U
#define SETTINGS_FPS_MARK_LOW (SETTINGS_FPS_MARK & 0x0FU)
#define SETTINGS_PAYLOAD_AUTO_SLEEP_MASK 0x1FU
#define SETTINGS_PAYLOAD_FEATURE_SHIFT 5U
#define SETTINGS_FEATURE_FLAGS_MASK 0x07U

#define CAMERA_SETTINGS_ROW_COUNT 10
#define CAMERA_SETTINGS_REVIEW 0
#define CAMERA_SETTINGS_FPS 1
#define CAMERA_SETTINGS_LIGHT 2
#define CAMERA_SETTINGS_RGB_RED 3
#define CAMERA_SETTINGS_RGB_GREEN 4
#define CAMERA_SETTINGS_RGB_BLUE 5
#define CAMERA_SETTINGS_FOLDER 6
#define CAMERA_SETTINGS_FORMAT 7
#define CAMERA_SETTINGS_SIZE 8
#define CAMERA_SETTINGS_VERSION 9

#define QR_SETTINGS_ROW_COUNT 7
#define QR_SETTINGS_RATE 0
#define QR_SETTINGS_FPS 1
#define QR_SETTINGS_LIGHT 2
#define QR_SETTINGS_RGB_RED 3
#define QR_SETTINGS_RGB_GREEN 4
#define QR_SETTINGS_RGB_BLUE 5
#define QR_SETTINGS_VERSION 6

#endif
