#ifndef HK_SETTINGS_CONFIG_H
#define HK_SETTINGS_CONFIG_H

#define SETTINGS_SAVE_DELAY_TICKS 25
#define SETTINGS_FLASH_SLOT0 0x007FE000UL
#define SETTINGS_FLASH_SLOT1 0x007FF000UL
#define SETTINGS_FLASH_SLOT_SIZE 4096U
#define SETTINGS_FLASH_MIN_CAPACITY_LOG2 23U
#define SETTINGS_MAGIC 0x484B5331UL
#define SETTINGS_STORAGE_VERSION 2U
#define SETTINGS_STORAGE_LEGACY_VERSION 1U
#define SETTINGS_APP_DATA_SIZE 80U
#define SETTINGS_RGB_MARK 0xC3U
#define SETTINGS_FPS_MARK 0xF5U
#define SETTINGS_CAMERA_MARK_V1 0xA5U
#define SETTINGS_CAMERA_MARK 0xA6U
#define SETTINGS_FPS_MARK_LOW (SETTINGS_FPS_MARK & 0x0FU)
#define SETTINGS_PAYLOAD_AUTO_SLEEP_MASK 0x1FU
#define SETTINGS_PAYLOAD_FEATURE_SHIFT 5U
#define SETTINGS_FEATURE_FLAGS_MASK 0x07U
#define SETTINGS_EXTERNAL_LINK_I2C_FLAG 0x02U
#define SETTINGS_UART_SPEED_SHIFT 1U
#define SETTINGS_UART_SPEED_MASK 0x06U
#define SETTINGS_UART_SPEED_MARK 0x08U

#endif
