#ifndef HACKYLENS_APP_H
#define HACKYLENS_APP_H

#include <hackylens/app/runtime.h>

#define HK_APP_SDK_VERSION_MAJOR 0U
#define HK_APP_SDK_VERSION_MINOR 2U
#define HK_APP_SDK_VERSION_PATCH 0U

#define HK_APP_SDK_RUNTIME_MINIMUM_MAJOR 0U
#define HK_APP_SDK_RUNTIME_MINIMUM_MINOR 2U
#define HK_APP_SDK_RUNTIME_MINIMUM_PATCH 0U
#define HK_APP_SDK_RUNTIME_MAXIMUM_EXCLUSIVE_MAJOR 0U
#define HK_APP_SDK_RUNTIME_MAXIMUM_EXCLUSIVE_MINOR 3U
#define HK_APP_SDK_RUNTIME_MAXIMUM_EXCLUSIVE_PATCH 0U

#define HK_APP_SDK_CAPABILITY_MINIMUM_MAJOR 0U
#define HK_APP_SDK_CAPABILITY_MINIMUM_MINOR 1U
#define HK_APP_SDK_CAPABILITY_MINIMUM_PATCH 0U
#define HK_APP_SDK_CAPABILITY_MAXIMUM_EXCLUSIVE_MAJOR 0U
#define HK_APP_SDK_CAPABILITY_MAXIMUM_EXCLUSIVE_MINOR 2U
#define HK_APP_SDK_CAPABILITY_MAXIMUM_EXCLUSIVE_PATCH 0U

#define HK_APP_SDK_MANIFEST_SCHEMA_MAJOR 1U

#endif
