#ifndef HK_MICROPYTHON_APP_CONFIG_H
#define HK_MICROPYTHON_APP_CONFIG_H

#include "../../core/hk_app.h"

#define HK_MICROPYTHON_SCREEN SCREEN_APP_SLOT_2
#define MICROPYTHON_LOG_LINES 7U
#define MICROPYTHON_LOG_COLUMNS 38U

#endif
