#ifndef HK_FILE_BROWSER_CONFIG_H
#define HK_FILE_BROWSER_CONFIG_H

#define FILES_MAX_ENTRIES 64
#define FILES_STACK_MAX 8
#define FILE_PREVIEW_MAX 2048
#define FILES_REPEAT_INITIAL_TICKS 3
#define FILES_REPEAT_NEXT_TICKS 1
#define FILES_OK_HOLD_US 700000ULL

#endif
