#ifndef HK_FILE_BROWSER_CONFIG_H
#define HK_FILE_BROWSER_CONFIG_H

#define FILES_MAX_ENTRIES 64
#define FILES_STACK_MAX 8
#define FILE_PREVIEW_MAX 2048
#define FILES_REPEAT_INITIAL_US 500000ULL
#define FILES_REPEAT_NEXT_US 180000ULL
#define FILES_OK_HOLD_US 700000ULL

#endif
