#ifndef PONG_CONFIG_H
#define PONG_CONFIG_H

#define PONG_DISPLAY_WIDTH 320
#define PONG_DISPLAY_HEIGHT 240
#define PONG_MENU_BAR_H 30
#define PONG_MENU_LINE 2
#define PONG_COLOR_BLACK 0x0000
#define PONG_COLOR_WHITE 0xFFFF
#define PONG_COLOR_GREEN 0x07E0

#define PONG_FIELD_X 2
#define PONG_FIELD_Y (PONG_MENU_BAR_H + 2)
#define PONG_FIELD_W (PONG_DISPLAY_WIDTH - 4)
#define PONG_FIELD_H (PONG_DISPLAY_HEIGHT - PONG_MENU_BAR_H - 4)
#define PONG_PADDLE_W 52
#define PONG_PADDLE_H 5
#define PONG_BALL_SIZE 6
#define PONG_FIXED_STEP_US 20000ULL
#define PONG_MAX_CATCH_UP_STEPS 8
#define PONG_PLAYER_Y (PONG_DISPLAY_HEIGHT - 14)
#define PONG_AI_Y (PONG_FIELD_Y + 10)
#define PONG_PADDLE_SPEED 6
#define PONG_AI_SPEED 4
#define PONG_AI_REACTION_TICKS 5
#define PONG_AI_DEAD_ZONE 3
#define PONG_AI_ERROR_PX 11
#define PONG_BALL_START_DX 2
#define PONG_BALL_START_DY 3
#define PONG_BALL_MAX_DX 7
#define PONG_BALL_MAX_DY 7
#define PONG_RALLY_SPEEDUP_EVERY 3
#define PONG_SERVE_DELAY_TICKS 18
#define PONG_FLASH_TICKS 3
#define PONG_TRAIL_LENGTH 2
#define PONG_TRAIL_COLOR 0x03E0
#define PONG_BALL_COLOR PONG_COLOR_WHITE
#define PONG_FLASH_COLOR PONG_COLOR_WHITE

#endif
