#ifndef HK_CONFIG_DEFAULT_H
#define HK_CONFIG_DEFAULT_H
#ifndef HACKYLENS_VERSION
#define HACKYLENS_VERSION "0.1.0"
#endif
#ifndef HK_ENABLE_APP_TERMINAL
#define HK_ENABLE_APP_TERMINAL 1
#endif
#ifndef HK_ENABLE_APP_CAMERA
#define HK_ENABLE_APP_CAMERA 1
#endif
#ifndef HK_ENABLE_APP_QR_CAMERA
#define HK_ENABLE_APP_QR_CAMERA 1
#endif
#ifndef HK_ENABLE_APP_FACE_DETECT
#define HK_ENABLE_APP_FACE_DETECT 1
#endif
#ifndef HK_ENABLE_APP_APRILTAG
#define HK_ENABLE_APP_APRILTAG 1
#endif
#ifndef HK_ENABLE_APP_FILES
#define HK_ENABLE_APP_FILES 1
#endif
#ifndef HK_ENABLE_APP_BUTTONS
#define HK_ENABLE_APP_BUTTONS 1
#endif
#ifndef HK_ENABLE_APP_PONG
#define HK_ENABLE_APP_PONG 1
#endif
#ifndef HK_ENABLE_APP_SETTINGS
#define HK_ENABLE_APP_SETTINGS 1
#endif
#ifndef HK_ENABLE_APP_SLEEP
#define HK_ENABLE_APP_SLEEP 1
#endif
#endif
