#ifndef HK_CONFIG_DEFAULT_H
#define HK_CONFIG_DEFAULT_H
#ifndef HACKYLENS_VERSION
#define HACKYLENS_VERSION "0.3.0"
#endif
#ifndef HK_MICROPYTHON_WDT_FAULT_INJECTION
#define HK_MICROPYTHON_WDT_FAULT_INJECTION 0
#endif
#endif
