#!/usr/bin/env python3
"""Generate immutable native app registry descriptors from a canonical model."""

from __future__ import annotations

import json
from typing import Any, Callable, Mapping


class RegistryGenerationError(ValueError):
    """The canonical app model cannot be represented by the fixed registry ABI."""


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _count_expression(name: str, c_type: str) -> str:
    return f"(uint16_t)(sizeof({name}) / sizeof({c_type}))"


def _request_rows(app: Mapping[str, Any]) -> list[tuple[Mapping[str, Any], bool]]:
    rows = [(request, False) for request in app["capabilities"]["required"]]
    rows.extend((request, True) for request in app["capabilities"]["optional"])
    return rows


def generated_header(model: Mapping[str, Any]) -> str:
    apps = list(model["apps"])
    if len(apps) > 254:
        raise RegistryGenerationError("fixed registry supports at most 254 apps")
    lines = [
        "/* Generated by tools/gen_app_composition.py; do not edit. */",
        "#ifndef HK_GENERATED_APP_REGISTRY_H",
        "#define HK_GENERATED_APP_REGISTRY_H",
        "",
        "#include <stdint.h>",
        "",
        "#include \"../../src/core/hk_app.h\"",
        "",
    ]
    for app in apps:
        lines.append(f"extern const hk_app_t {app['generated_symbol']};")
    if apps:
        lines.append("")
    lines.extend([
        "extern const hk_app_t *const g_hk_generated_apps[];",
        "extern const uint8_t g_hk_generated_app_count;",
        "extern const hk_autostart_id_t g_hk_reserved_autostart_ids[];",
        "extern const uint8_t g_hk_reserved_autostart_id_count;",
        "extern const hk_app_t *const g_menu_items[];",
        "extern const uint8_t g_menu_item_count;",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def generated_source(
    model: Mapping[str, Any],
    enable_definition: Callable[[str], str],
) -> str:
    apps = list(model["apps"])
    if len(apps) > 254:
        raise RegistryGenerationError("fixed registry supports at most 254 apps")
    lines = [
        "/* Generated by tools/gen_app_composition.py; do not edit. */",
        "#include \"registry.h\"",
        "",
        "#include <stddef.h>",
        "",
        "#include \"hk_config.h\"",
        "",
    ]

    for app_index, app in enumerate(apps):
        guard = enable_definition(str(app["id"]))
        lifecycle = str(app["lifecycle"])
        entry_type = (
            "hk_legacy_app_entry_t" if lifecycle == "legacy"
            else "hk_app_v2_entry_t"
        )
        icon_symbol = str(app["id"]).replace("-", "_") + "_draw_icon"
        lines.extend([
            f"#if {guard}",
            f"extern const {entry_type} {app['entry']};",
            f"extern void {icon_symbol}("
            "uint16_t x, uint16_t y, uint16_t color, uint16_t bg);",
            "",
        ])

        requests = _request_rows(app)
        for request_index, (request, _) in enumerate(requests):
            features = list(request["features"])
            if not features:
                continue
            feature_name = f"s_app_{app_index}_request_{request_index}_features"
            lines.append(f"static const char *const {feature_name}[] = {{")
            for feature in features:
                lines.append(f"    {_c_string(str(feature))},")
            lines.extend(["};", ""])

        request_array = f"s_app_{app_index}_capabilities"
        if requests:
            lines.append(
                f"static const hk_app_capability_request_t {request_array}[] = {{"
            )
            for request_index, (request, optional) in enumerate(requests):
                features = list(request["features"])
                feature_name = (
                    f"s_app_{app_index}_request_{request_index}_features"
                    if features else "NULL"
                )
                fallback = (
                    _c_string(str(request["fallback"]))
                    if optional else "NULL"
                )
                lines.extend([
                    "    {",
                    f"        {_c_string(str(request['id']))}, {int(request['instance'])}U,",
                    f"        {_c_string(str(request['minimum']))},",
                    f"        {_c_string(str(request['maximum_exclusive']))},",
                    f"        {feature_name}, {len(features)}U,",
                    f"        {fallback}, {1 if optional else 0}U,",
                    "    },",
                ])
            lines.extend(["};", ""])

        services = list(app["services"])
        service_array = f"s_app_{app_index}_services"
        if services:
            lines.append(f"static const hk_app_service_request_t {service_array}[] = {{")
            for service in services:
                lines.append(
                    "    {"
                    f"{_c_string(str(service['id']))}, "
                    f"{_c_string(str(service['namespace']))}"
                    "},"
                )
            lines.extend(["};", ""])

        capability_pointer = request_array if requests else "NULL"
        capability_count = (
            _count_expression(request_array, "hk_app_capability_request_t")
            if requests else "0U"
        )
        service_pointer = service_array if services else "NULL"
        service_count = (
            _count_expression(service_array, "hk_app_service_request_t")
            if services else "0U"
        )
        entry_member = "legacy" if lifecycle == "legacy" else "v2"
        lifecycle_value = (
            "HK_APP_LIFECYCLE_LEGACY" if lifecycle == "legacy"
            else "HK_APP_LIFECYCLE_V2"
        )
        limits = app["limits"]
        lines.extend([
            f"const hk_app_t {app['generated_symbol']} = {{",
            "    .struct_size = sizeof(hk_app_t),",
            "    .struct_version = HK_APP_DESCRIPTOR_VERSION,",
            f"    .id = {_c_string(str(app['id']))},",
            f"    .title = {_c_string(str(app['name']))},",
            f"    .version = {_c_string(str(app['version']))},",
            f"    .menu_order = {int(app['menu']['order'])}U,",
            f"    .menu_visible = {1 if app['menu']['visible'] else 0}U,",
            f"    .autostart_id = {int(app['autostart']['id'])}U,",
            f"    .autostart_eligible = {1 if app['autostart']['eligible'] else 0}U,",
            f"    .lifecycle = {lifecycle_value},",
            f"    .entry = {{.{entry_member} = &{app['entry']}}},",
            f"    .help = {_c_string(str(app['metadata']['help']))},",
            f"    .debug_help = {_c_string(str(app['metadata']['debug']))},",
            "    .limits = {",
            f"        {int(limits['static_ram_bytes'])}U,",
            f"        {int(limits['stack_bytes'])}U,",
            f"        {int(limits['state_bytes'])}U,",
            "        HK_APP_DESCRIPTOR_STATE_ALIGNMENT,",
            f"        {int(limits['tick_interval_us'])}U,",
            f"        {int(limits['tick_budget_us'])}U,",
            f"        {int(limits['render_budget_us'])}U,",
            "    },",
            f"    .capabilities = {capability_pointer},",
            f"    .capability_count = {capability_count},",
            f"    .services = {service_pointer},",
            f"    .service_count = {service_count},",
            f"    .draw_icon = {icon_symbol},",
            "};",
            f"#endif /* {guard} */",
            "",
        ])

    lines.append("const hk_app_t *const g_hk_generated_apps[] = {")
    for app in apps:
        guard = enable_definition(str(app["id"]))
        lines.extend([
            f"#if {guard}",
            f"    &{app['generated_symbol']},",
            "#endif",
        ])
    lines.extend([
        "    NULL,",
        "};",
        "const uint8_t g_hk_generated_app_count =",
        "    (uint8_t)((sizeof(g_hk_generated_apps) /",
        "               sizeof(g_hk_generated_apps[0])) - 1U);",
        "",
        "const hk_autostart_id_t g_hk_reserved_autostart_ids[] = {",
    ])
    for app in sorted(
        (item for item in apps if item["autostart"]["eligible"]),
        key=lambda item: int(item["autostart"]["id"]),
    ):
        lines.append(f"    {int(app['autostart']['id'])}U,")
    lines.extend([
        "    HK_AUTOSTART_OFF,",
        "};",
        "const uint8_t g_hk_reserved_autostart_id_count =",
        "    (uint8_t)((sizeof(g_hk_reserved_autostart_ids) /",
        "               sizeof(g_hk_reserved_autostart_ids[0])) - 1U);",
        "",
        "const hk_app_t *const g_menu_items[] = {",
    ])
    for app in sorted(
        (item for item in apps if item["menu"]["visible"]),
        key=lambda item: (int(item["menu"]["order"]), str(item["id"])),
    ):
        guard = enable_definition(str(app["id"]))
        lines.extend([
            f"#if {guard}",
            f"    &{app['generated_symbol']},",
            "#endif",
        ])
    lines.extend([
        "    NULL,",
        "};",
        "const uint8_t g_menu_item_count =",
        "    (uint8_t)((sizeof(g_menu_items) /",
        "               sizeof(g_menu_items[0])) - 1U);",
        "",
    ])
    return "\n".join(lines)
