#!/usr/bin/env python3
"""Generate immutable native app registry descriptors from a canonical model."""

from __future__ import annotations

import json
from typing import Any, Callable, Mapping


class RegistryGenerationError(ValueError):
    """The canonical app model cannot be represented by the fixed registry ABI."""


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generated_header(model: Mapping[str, Any]) -> str:
    apps = list(model["apps"])
    if len(apps) > 254:
        raise RegistryGenerationError("fixed registry supports at most 254 apps")
    lines = [
        "/* Generated by tools/gen_app_composition.py; do not edit. */",
        "#ifndef HK_GENERATED_APP_REGISTRY_H",
        "#define HK_GENERATED_APP_REGISTRY_H",
        "",
        "#include <stdint.h>",
        "",
        "#include \"../../src/core/hk_app.h\"",
        "",
    ]
    for app in apps:
        lines.append(f"extern const hk_app_t {app['generated_symbol']};")
    if apps:
        lines.append("")
    lines.extend([
        "extern const hk_app_t *const g_hk_generated_apps[];",
        "extern const uint8_t g_hk_generated_app_count;",
        "extern const hk_autostart_id_t g_hk_reserved_autostart_ids[];",
        "extern const uint8_t g_hk_reserved_autostart_id_count;",
        "extern const hk_app_t *const g_menu_items[];",
        "extern const uint8_t g_menu_item_count;",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def generated_source(
    model: Mapping[str, Any],
    enable_definition: Callable[[str], str],
) -> str:
    apps = list(model["apps"])
    if len(apps) > 254:
        raise RegistryGenerationError("fixed registry supports at most 254 apps")
    lines = [
        "/* Generated by tools/gen_app_composition.py; do not edit. */",
        "#include \"registry.h\"",
        "",
        "#include <stddef.h>",
        "",
        "#include \"hk_config.h\"",
        "",
    ]

    for app_index, app in enumerate(apps):
        guard = enable_definition(str(app["id"]))
        entry_type = "hk_app_v2_entry_t"
        debug_symbol = app["metadata"].get("debug_entry") or "NULL"
        icon_symbol = str(app["id"]).replace("-", "_") + "_draw_icon"
        lines.extend([
            f"#if {guard}",
            f"extern const {entry_type} {app['entry']};",
            f"extern void {icon_symbol}("
            "uint16_t x, uint16_t y, uint16_t color, uint16_t bg);",
            "",
        ])

        if debug_symbol != "NULL":
            lines.append(f"extern uint8_t {debug_symbol}(const char *command);")

        limits = app["limits"]
        lines.extend([
            f"const hk_app_t {app['generated_symbol']} = {{",
            "    .struct_size = sizeof(hk_app_t),",
            "    .struct_version = HK_APP_DESCRIPTOR_VERSION,",
            f"    .id = {_c_string(str(app['id']))},",
            f"    .title = {_c_string(str(app['name']))},",
            f"    .version = {_c_string(str(app['version']))},",
            f"    .menu_order = {int(app['menu']['order'])}U,",
            f"    .menu_visible = {1 if app['menu']['visible'] else 0}U,",
            f"    .autostart_id = {int(app['autostart']['id'])}U,",
            f"    .autostart_eligible = {1 if app['autostart']['eligible'] else 0}U,",
            f"    .entry = &{app['entry']},",
            f"    .help = {_c_string(str(app['metadata']['help']))},",
            f"    .debug_help = {_c_string(str(app['metadata']['debug']))},",
            "    .limits = {",
            f"        {int(limits['static_ram_bytes'])}U,",
            f"        {int(limits['stack_bytes'])}U,",
            f"        {int(limits['state_bytes'])}U,",
            "        HK_APP_DESCRIPTOR_STATE_ALIGNMENT,",
            f"        {int(limits['tick_interval_us'])}U,",
            f"        {int(limits['tick_budget_us'])}U,",
            f"        {int(limits['render_budget_us'])}U,",
            "    },",
            f"    .draw_icon = {icon_symbol},",
            f"    .debug_command = {debug_symbol},",
            "};",
            f"#endif /* {guard} */",
            "",
        ])

    lines.append("const hk_app_t *const g_hk_generated_apps[] = {")
    for app in apps:
        guard = enable_definition(str(app["id"]))
        lines.extend([
            f"#if {guard}",
            f"    &{app['generated_symbol']},",
            "#endif",
        ])
    lines.extend([
        "    NULL,",
        "};",
        "const uint8_t g_hk_generated_app_count =",
        "    (uint8_t)((sizeof(g_hk_generated_apps) /",
        "               sizeof(g_hk_generated_apps[0])) - 1U);",
        "",
        "const hk_autostart_id_t g_hk_reserved_autostart_ids[] = {",
    ])
    for app in sorted(
        (item for item in apps if item["autostart"]["eligible"]),
        key=lambda item: int(item["autostart"]["id"]),
    ):
        lines.append(f"    {int(app['autostart']['id'])}U,")
    lines.extend([
        "    HK_AUTOSTART_OFF,",
        "};",
        "const uint8_t g_hk_reserved_autostart_id_count =",
        "    (uint8_t)((sizeof(g_hk_reserved_autostart_ids) /",
        "               sizeof(g_hk_reserved_autostart_ids[0])) - 1U);",
        "",
        "const hk_app_t *const g_menu_items[] = {",
    ])
    for app in sorted(
        (item for item in apps if item["menu"]["visible"]),
        key=lambda item: (int(item["menu"]["order"]), str(item["id"])),
    ):
        guard = enable_definition(str(app["id"]))
        lines.extend([
            f"#if {guard}",
            f"    &{app['generated_symbol']},",
            "#endif",
        ])
    lines.extend([
        "    NULL,",
        "};",
        "const uint8_t g_menu_item_count =",
        "    (uint8_t)((sizeof(g_menu_items) /",
        "               sizeof(g_menu_items[0])) - 1U);",
        "",
    ])
    return "\n".join(lines)
