#!/usr/bin/env python3
"""Bootstrap local HackyLens dependencies under hackylens/_deps."""

from __future__ import annotations

import argparse
import ast
import binascii
import re
import shutil
import subprocess
import sys
import tarfile
import urllib.request
import zlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEPS = ROOT / "_deps"
DOWNLOADS = DEPS / "downloads"

SDK_DIR = DEPS / "kendryte-standalone-sdk"
KFLASH_REF_DIR = DEPS / "kflash.py-reference"
ISP_STUB = DEPS / "isp_prog.bin"

SDK_REPO = "https://github.com/kendryte/kendryte-standalone-sdk"
KFLASH_REPO = "https://github.com/sipeed/kflash.py"
TOOLCHAIN_URL = (
    "https://github.com/kendryte/kendryte-gnu-toolchain/releases/download/"
    "v8.2.0-20190409/kendryte-toolchain-win-i386-8.2.0-20190409.tar.xz"
)
TOOLCHAIN_ARCHIVE = DOWNLOADS / "kendryte-toolchain-win-i386-8.2.0-20190409.tar.xz"


def run(cmd: list[str], cwd: Path | None = None) -> None:
    print("+ " + " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def ensure_git_checkout(path: Path, repo: str) -> None:
    if (path / ".git").is_dir():
        print(f"[OK] checkout exists: {path}")
        return
    if path.exists() and any(path.iterdir()):
        print(f"[OK] directory exists: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    git = shutil.which("git")
    if not git:
        raise RuntimeError("git is required to clone dependencies")
    run([git, "clone", repo, str(path)])


def download_file(url: str, out: Path) -> None:
    if out.is_file() and out.stat().st_size > 0:
        print(f"[OK] download exists: {out}")
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_suffix(out.suffix + ".part")
    print(f"[GET] {url}")
    with urllib.request.urlopen(url) as src, tmp.open("wb") as dst:
        shutil.copyfileobj(src, dst, length=1024 * 1024)
    tmp.replace(out)


def safe_extract_tar(archive: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    root = destination.resolve()
    with tarfile.open(archive, "r:*") as tar:
        members = tar.getmembers()
        for member in members:
            target = (destination / member.name).resolve()
            if root != target and root not in target.parents:
                raise RuntimeError(f"refusing unsafe tar member: {member.name}")
        tar.extractall(destination, members=members)


def find_toolchain_bin() -> Path | None:
    names = ("riscv64-unknown-elf-gcc.exe", "riscv64-unknown-elf-gcc")
    for name in names:
        for gcc in DEPS.rglob(name):
            if gcc.is_file():
                return gcc.parent
    return None


def ensure_toolchain() -> Path:
    existing = find_toolchain_bin()
    if existing:
        print(f"[OK] toolchain: {existing}")
        return existing

    download_file(TOOLCHAIN_URL, TOOLCHAIN_ARCHIVE)
    print(f"[EXTRACT] {TOOLCHAIN_ARCHIVE}")
    safe_extract_tar(TOOLCHAIN_ARCHIVE, DEPS)

    found = find_toolchain_bin()
    if not found:
        raise RuntimeError("toolchain extracted, but riscv64-unknown-elf-gcc was not found")
    print(f"[OK] toolchain: {found}")
    return found


def extract_isp_stub() -> None:
    if ISP_STUB.is_file() and ISP_STUB.stat().st_size > 0:
        print(f"[OK] ISP stub: {ISP_STUB}")
        return

    source = KFLASH_REF_DIR / "kflash.py"
    if not source.is_file():
        raise RuntimeError(f"kflash reference missing: {source}")

    text = source.read_text(encoding="utf-8")
    match = re.search(r"ISP_PROG\s*=\s*('(?:[^'\\]|\\.)*')", text)
    if not match:
        raise RuntimeError("could not locate ISP_PROG in kflash.py reference")

    compressed_hex = ast.literal_eval(match.group(1))
    data = zlib.decompress(binascii.unhexlify(compressed_hex))
    ISP_STUB.write_bytes(data)
    print(f"[OK] ISP stub: {ISP_STUB} ({len(data)} bytes)")


def write_env(toolchain_bin: Path) -> None:
    env_path = ROOT / "env.ps1"
    sdk = SDK_DIR.resolve()
    toolchain = toolchain_bin.resolve()
    content = f"""# Generated by hackylens/tools/bootstrap_deps.py
$env:KENDRYTE_SDK_DIR = "{sdk}"
$env:KENDRYTE_TOOLCHAIN_BIN = "{toolchain}"
$env:Path = "{toolchain};" + $env:Path
Write-Host "[HackyLens] KENDRYTE_SDK_DIR=$env:KENDRYTE_SDK_DIR"
Write-Host "[HackyLens] KENDRYTE_TOOLCHAIN_BIN=$env:KENDRYTE_TOOLCHAIN_BIN"
"""
    env_path.write_text(content, encoding="utf-8")
    print(f"[OK] env: {env_path}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Bootstrap local HackyLens dependencies")
    parser.add_argument("--skip-download", action="store_true", help="Only validate existing dependencies")
    args = parser.parse_args(argv)

    DEPS.mkdir(parents=True, exist_ok=True)
    if not args.skip_download:
        ensure_git_checkout(SDK_DIR, SDK_REPO)
        ensure_git_checkout(KFLASH_REF_DIR, KFLASH_REPO)

    if not SDK_DIR.is_dir():
        raise SystemExit(f"missing SDK checkout: {SDK_DIR}")
    if not KFLASH_REF_DIR.is_dir():
        raise SystemExit(f"missing kflash reference checkout: {KFLASH_REF_DIR}")

    toolchain = ensure_toolchain()
    extract_isp_stub()
    write_env(toolchain)

    print("[DONE] run: . hackylens\\env.ps1")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        raise SystemExit(130)
    except Exception as exc:
        print(f"[ERR] {exc}", file=sys.stderr)
        raise SystemExit(1)
