schema = 2

[apps.terminal]
requires = ["display", "buttons"]
required_capabilities = []
optional_capabilities = []

[apps.camera]
requires = ["display", "camera", "buttons", "lights", "sd-card"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us", "sleep-until"] },
]
optional_capabilities = []

[apps.qr-camera]
requires = ["display", "camera", "buttons", "lights", "sd-card"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us"] },
]
optional_capabilities = []

[apps.face-detect]
requires = ["display", "camera", "buttons", "lights", "sd-card"]
required_capabilities = []
optional_capabilities = []

[apps.apriltag]
requires = ["display", "camera", "buttons", "lights"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us", "sleep-until"] },
]
optional_capabilities = []

[apps.object-detect]
requires = ["display", "camera", "buttons", "lights", "sd-card"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us"] },
]
optional_capabilities = []

[apps.files]
requires = ["display", "buttons", "sd-card"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us"] },
]
optional_capabilities = []

[apps.buttons]
requires = ["display", "buttons"]
required_capabilities = []
optional_capabilities = []

[apps.pong]
requires = ["display", "buttons"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us"] },
]
optional_capabilities = []

[apps.settings]
requires = ["display", "buttons", "lights"]
required_capabilities = []
optional_capabilities = []

[apps.sleep]
requires = ["display", "buttons", "lights"]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us"] },
]
optional_capabilities = []

[apps.micropython]
requires = [
  "display",
  "buttons",
  "lights",
  "internal-flash",
  "external-uart",
  "external-i2c",
]
required_capabilities = [
  { id = "hackylens.cap.time", instance = 0, minimum = "0.1.0", maximum_exclusive = "0.2.0", features = ["monotonic-us", "sleep-until"] },
]
optional_capabilities = []
